export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CART_SAVE_SHIPPING = "CART_SAVE_SHIPPING";

export const CART_SAVE_PAYMENT = "CART_SAVE_PAYMENT";
export const LIKE_SAVE_SUCCESS = "LIKE_SAVE_SUCCESS";
export const LIKE_SAVE_REQUEST = "LIKE_SAVE_REQUEST"
export const LIKE_SAVE_FAILURE = "LIKE_SAVE_FAILURE"

