export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CART_SAVE_SHIPPING = "CART_SAVE_SHIPPING";

export const CART_SAVE_PAYMENT = "CART_SAVE_PAYMENT";
